//     Morse Code Practice
// 
//     Copyright (C)  2024 Tom Stevelt
// 
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as
//     published by the Free Software Foundation, either version 3 of the
//     License, or (at your option) any later version.
// 
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU Affero General Public License for more details.
// 
//     You should have received a copy of the GNU Affero General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.

var SpeedWPM = 5;
var DotMS = 100;
var DashMS = 3 * DotMS;
var InterMS = 3 * DotMS;
var IntraMS = DotMS;
var WordMS = 7 * DotMS;

var SineSeed = 0.0;

var ErrorCount = 0;
var TotalCount = 0;

var Letters = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.', ',', '/', '?', '@' ];

var Koch = [ 'k', 'm', 'u', 'r', 'e', 's', 'n', 'a', 'p', 't', 'l', 'w', 'i', '.', 'j', 'z', '=', 'f', 'o', 'y', ',', 'v', 'g', '5', '/', 'q', '9', '2', 'h', '3', '8', 'b', '1', 'c', '?', '4', '7',  'd', '6', '0', 'x' ];


var audio;
var audioCtx;
var oscillator;
var biquadFilter;
var gainNode;
var type = 'sine';
var frequency = 440;
var when = 1.0;

var CodeBook = [
//  [ '!','-.-.--' ],
//  [ '$','...-..-' ],
//  [ '&','.-...' ],
//  [ '&quot;','.-..-.' ],
//  [ ''','.----.' ],
//  [ '(','-.--.' ],
//  [ ')','-.--.-' ],
//  [ '+','.-.-.' ],
//  [ '-','-....-' ],
//  [ ':','---...' ],
//  [ ';','-.-.-.' ],
//  [ '_','..--.-' ],
//  [ '|','--...-' ],

  [ ',','--..--' ], // comma
  [ '.','.-.-.-' ], // period
  [ '/','-..-.' ],  // slash
  [ '0','-----' ],
  [ '1','.----' ],
  [ '2','..---' ],
  [ '3','...--' ],
  [ '4','....-' ],
  [ '5','.....' ],
  [ '6','-....' ],
  [ '7','--...' ],
  [ '8','---..' ],
  [ '9','----.' ],
  [ '=','-...-' ], // equals
  [ '?','..--..' ], // question mark
  [ '@','.--.-.' ], // at sign
  [ 'A','.-' ],
  [ 'B','-...' ],
  [ 'C','-.-.' ],
  [ 'D','-..' ],
  [ 'E','.' ],
  [ 'F','..-.' ],
  [ 'G','--.' ],
  [ 'H','....' ],
  [ 'I','..' ],
  [ 'J','.---' ],
  [ 'K','-.-' ],
  [ 'L','.-..' ],
  [ 'M','--' ],
  [ 'N','-.' ],
  [ 'O','---' ],
  [ 'P','.--.' ],
  [ 'Q','--.-' ],
  [ 'R','.-.' ],
  [ 'S','...' ],
  [ 'T','-' ],
  [ 'U','..-' ],
  [ 'V','...-' ],
  [ 'W','.--' ],
  [ 'X','-..-' ],
  [ 'Y','-.--' ],
  [ 'Z','--..' ]
];

var Words = [
 [ 'aargh', 0 ],
 [ 'aback', 0 ],
 [ 'abaft', 0 ],
 [ 'aboon', 0 ],
 [ 'about', 0 ],
 [ 'above', 0 ],
 [ 'abuse', 0 ],
 [ 'abyss', 0 ],
 [ 'accel', 0 ],
 [ 'acute', 0 ],
 [ 'adieu', 0 ],
 [ 'adios', 0 ],
 [ 'admit', 0 ],
 [ 'adopt', 0 ],
 [ 'adore', 0 ],
 [ 'adown', 0 ],
 [ 'adult', 0 ],
 [ 'afoot', 0 ],
 [ 'afore', 0 ],
 [ 'afoul', 0 ],
 [ 'after', 0 ],
 [ 'again', 0 ],
 [ 'agape', 0 ],
 [ 'agent', 0 ],
 [ 'agogo', 0 ],
 [ 'agone', 0 ],
 [ 'agree', 0 ],
 [ 'ahead', 0 ],
 [ 'ahull', 0 ],
 [ 'alack', 0 ],
 [ 'alife', 0 ],
 [ 'alike', 0 ],
 [ 'alive', 0 ],
 [ 'allow', 0 ],
 [ 'aloft', 0 ],
 [ 'aloha', 0 ],
 [ 'alone', 0 ],
 [ 'along', 0 ],
 [ 'aloof', 0 ],
 [ 'aloud', 0 ],
 [ 'alter', 0 ],
 [ 'amiss', 0 ],
 [ 'among', 0 ],
 [ 'ample', 0 ],
 [ 'amply', 0 ],
 [ 'anger', 0 ],
 [ 'angry', 0 ],
 [ 'ankle', 0 ],
 [ 'apace', 0 ],
 [ 'apart', 0 ],
 [ 'apple', 0 ],
 [ 'apply', 0 ],
 [ 'aptly', 0 ],
 [ 'arear', 0 ],
 [ 'argue', 0 ],
 [ 'arise', 0 ],
 [ 'aroma', 0 ],
 [ 'aside', 0 ],
 [ 'askew', 0 ],
 [ 'audio', 0 ],
 [ 'audit', 0 ],
 [ 'aural', 0 ],
 [ 'avoid', 0 ],
 [ 'award', 0 ],
 [ 'aware', 0 ],
 [ 'awful', 0 ],
 [ 'badly', 0 ],
 [ 'bally', 0 ],
 [ 'basic', 0 ],
 [ 'basis', 0 ],
 [ 'basta', 0 ],
 [ 'beach', 0 ],
 [ 'begad', 0 ],
 [ 'began', 0 ],
 [ 'begin', 0 ],
 [ 'below', 0 ],
 [ 'birth', 0 ],
 [ 'black', 0 ],
 [ 'blame', 0 ],
 [ 'bless', 0 ],
 [ 'blind', 0 ],
 [ 'block', 0 ],
 [ 'blood', 0 ],
 [ 'blunt', 0 ],
 [ 'board', 0 ],
 [ 'braid', 0 ],
 [ 'brain', 0 ],
 [ 'brave', 0 ],
 [ 'bravo', 0 ],
 [ 'bread', 0 ],
 [ 'break', 0 ],
 [ 'brick', 0 ],
 [ 'brief', 0 ],
 [ 'bring', 0 ],
 [ 'brisk', 0 ],
 [ 'broad', 0 ],
 [ 'brown', 0 ],
 [ 'brush', 0 ],
 [ 'build', 0 ],
 [ 'bumpy', 0 ],
 [ 'burst', 0 ],
 [ 'buyer', 0 ],
 [ 'canny', 0 ],
 [ 'carry', 0 ],
 [ 'catch', 0 ],
 [ 'cause', 0 ],
 [ 'chain', 0 ],
 [ 'chair', 0 ],
 [ 'charm', 0 ],
 [ 'cheap', 0 ],
 [ 'check', 0 ],
 [ 'chest', 0 ],
 [ 'chief', 0 ],
 [ 'child', 0 ],
 [ 'china', 0 ],
 [ 'chive', 0 ],
 [ 'chord', 0 ],
 [ 'circa', 0 ],
 [ 'civil', 0 ],
 [ 'claim', 0 ],
 [ 'clasp', 0 ],
 [ 'class', 0 ],
 [ 'clean', 0 ],
 [ 'clear', 0 ],
 [ 'click', 0 ],
 [ 'climb', 0 ],
 [ 'clock', 0 ],
 [ 'close', 0 ],
 [ 'cloud', 0 ],
 [ 'coach', 0 ],
 [ 'coast', 0 ],
 [ 'count', 0 ],
 [ 'court', 0 ],
 [ 'cover', 0 ],
 [ 'coyly', 0 ],
 [ 'crave', 0 ],
 [ 'crazy', 0 ],
 [ 'cream', 0 ],
 [ 'crest', 0 ],
 [ 'crime', 0 ],
 [ 'cross', 0 ],
 [ 'crowd', 0 ],
 [ 'crown', 0 ],
 [ 'cumin', 0 ],
 [ 'cycle', 0 ],
 [ 'daily', 0 ],
 [ 'damme', 0 ],
 [ 'dance', 0 ],
 [ 'death', 0 ],
 [ 'depth', 0 ],
 [ 'diary', 0 ],
 [ 'dimly', 0 ],
 [ 'dirty', 0 ],
 [ 'ditto', 0 ],
 [ 'doubt', 0 ],
 [ 'draft', 0 ],
 [ 'drama', 0 ],
 [ 'drape', 0 ],
 [ 'dream', 0 ],
 [ 'dregs', 0 ],
 [ 'dress', 0 ],
 [ 'drink', 0 ],
 [ 'drive', 0 ],
 [ 'dryly', 0 ],
 [ 'dully', 0 ],
 [ 'dumpy', 0 ],
 [ 'dusky', 0 ],
 [ 'dwell', 0 ],
 [ 'early', 0 ],
 [ 'earth', 0 ],
 [ 'elite', 0 ],
 [ 'ember', 0 ],
 [ 'empty', 0 ],
 [ 'enact', 0 ],
 [ 'enemy', 0 ],
 [ 'enjoy', 0 ],
 [ 'enter', 0 ],
 [ 'entry', 0 ],
 [ 'equal', 0 ],
 [ 'error', 0 ],
 [ 'evade', 0 ],
 [ 'event', 0 ],
 [ 'evoke', 0 ],
 [ 'exact', 0 ],
 [ 'exist', 0 ],
 [ 'extra', 0 ],
 [ 'fable', 0 ],
 [ 'faint', 0 ],
 [ 'faith', 0 ],
 [ 'false', 0 ],
 [ 'fatly', 0 ],
 [ 'fault', 0 ],
 [ 'feyly', 0 ],
 [ 'field', 0 ],
 [ 'fifth', 0 ],
 [ 'fight', 0 ],
 [ 'final', 0 ],
 [ 'first', 0 ],
 [ 'fitly', 0 ],
 [ 'flair', 0 ],
 [ 'floor', 0 ],
 [ 'fluke', 0 ],
 [ 'flute', 0 ],
 [ 'focus', 0 ],
 [ 'folly', 0 ],
 [ 'force', 0 ],
 [ 'forte', 0 ],
 [ 'forth', 0 ],
 [ 'frame', 0 ],
 [ 'frank', 0 ],
 [ 'fresh', 0 ],
 [ 'frick', 0 ],
 [ 'front', 0 ],
 [ 'fruit', 0 ],
 [ 'fully', 0 ],
 [ 'funny', 0 ],
 [ 'gaily', 0 ],
 [ 'gauze', 0 ],
 [ 'gayly', 0 ],
 [ 'ghost', 0 ],
 [ 'giant', 0 ],
 [ 'giddy', 0 ],
 [ 'glass', 0 ],
 [ 'gloom', 0 ],
 [ 'godly', 0 ],
 [ 'golly', 0 ],
 [ 'gorge', 0 ],
 [ 'grand', 0 ],
 [ 'grant', 0 ],
 [ 'grape', 0 ],
 [ 'grasp', 0 ],
 [ 'grass', 0 ],
 [ 'gratz', 0 ],
 [ 'great', 0 ],
 [ 'green', 0 ],
 [ 'gross', 0 ],
 [ 'group', 0 ],
 [ 'guess', 0 ],
 [ 'guide', 0 ],
 [ 'gusty', 0 ],
 [ 'hallo', 0 ],
 [ 'haply', 0 ],
 [ 'happy', 0 ],
 [ 'harsh', 0 ],
 [ 'haste', 0 ],
 [ 'havoc', 0 ],
 [ 'heart', 0 ],
 [ 'heavy', 0 ],
 [ 'hella', 0 ],
 [ 'hence', 0 ],
 [ 'henry', 0 ],
 [ 'hilly', 0 ],
 [ 'hippy', 0 ],
 [ 'horse', 0 ],
 [ 'hotel', 0 ],
 [ 'hotly', 0 ],
 [ 'house', 0 ],
 [ 'hovel', 0 ],
 [ 'howay', 0 ],
 [ 'howdy', 0 ],
 [ 'hullo', 0 ],
 [ 'human', 0 ],
 [ 'hunch', 0 ],
 [ 'huzza', 0 ],
 [ 'icily', 0 ],
 [ 'ideal', 0 ],
 [ 'image', 0 ],
 [ 'imply', 0 ],
 [ 'index', 0 ],
 [ 'inept', 0 ],
 [ 'inert', 0 ],
 [ 'infra', 0 ],
 [ 'inner', 0 ],
 [ 'input', 0 ],
 [ 'intl.', 0 ],
 [ 'irate', 0 ],
 [ 'issue', 0 ],
 [ 'ivory', 0 ],
 [ 'jaded', 0 ],
 [ 'japan', 0 ],
 [ 'jazzy', 0 ],
 [ 'jesus', 0 ],
 [ 'jildi', 0 ],
 [ 'joint', 0 ],
 [ 'jolly', 0 ],
 [ 'jones', 0 ],
 [ 'joust', 0 ],
 [ 'judge', 0 ],
 [ 'juice', 0 ],
 [ 'jumbo', 0 ],
 [ 'jumpy', 0 ],
 [ 'kapow', 0 ],
 [ 'kinky', 0 ],
 [ 'knack', 0 ],
 [ 'knave', 0 ],
 [ 'knead', 0 ],
 [ 'knife', 0 ],
 [ 'kudos', 0 ],
 [ 'lanky', 0 ],
 [ 'large', 0 ],
 [ 'latch', 0 ],
 [ 'laugh', 0 ],
 [ 'laura', 0 ],
 [ 'laxly', 0 ],
 [ 'layer', 0 ],
 [ 'learn', 0 ],
 [ 'leave', 0 ],
 [ 'legal', 0 ],
 [ 'lento', 0 ],
 [ 'level', 0 ],
 [ 'lewis', 0 ],
 [ 'light', 0 ],
 [ 'limit', 0 ],
 [ 'local', 0 ],
 [ 'lolly', 0 ],
 [ 'loose', 0 ],
 [ 'lordy', 0 ],
 [ 'louie', 0 ],
 [ 'lowly', 0 ],
 [ 'lucky', 0 ],
 [ 'lunch', 0 ],
 [ 'lurid', 0 ],
 [ 'madly', 0 ],
 [ 'magic', 0 ],
 [ 'major', 0 ],
 [ 'march', 0 ],
 [ 'marry', 0 ],
 [ 'match', 0 ],
 [ 'maybe', 0 ],
 [ 'metal', 0 ],
 [ 'minor', 0 ],
 [ 'minus', 0 ],
 [ 'mirth', 0 ],
 [ 'mixed', 0 ],
 [ 'model', 0 ],
 [ 'money', 0 ],
 [ 'month', 0 ],
 [ 'moody', 0 ],
 [ 'moral', 0 ],
 [ 'motor', 0 ],
 [ 'mourn', 0 ],
 [ 'mouth', 0 ],
 [ 'mower', 0 ],
 [ 'muggy', 0 ],
 [ 'music', 0 ],
 [ 'naked', 0 ],
 [ 'nanny', 0 ],
 [ 'nappy', 0 ],
 [ 'nasty', 0 ],
 [ 'naval', 0 ],
 [ 'neath', 0 ],
 [ 'nerve', 0 ],
 [ 'never', 0 ],
 [ 'newly', 0 ],
 [ 'nifty', 0 ],
 [ 'night', 0 ],
 [ 'nobly', 0 ],
 [ 'noise', 0 ],
 [ 'north', 0 ],
 [ 'novel', 0 ],
 [ 'nudge', 0 ],
 [ 'nurse', 0 ],
 [ 'occur', 0 ],
 [ 'oddly', 0 ],
 [ 'offer', 0 ],
 [ 'often', 0 ],
 [ 'olive', 0 ],
 [ 'onset', 0 ],
 [ 'oomph', 0 ],
 [ 'order', 0 ],
 [ 'oread', 0 ],
 [ 'other', 0 ],
 [ 'ought', 0 ],
 [ 'ounce', 0 ],
 [ 'outer', 0 ],
 [ 'ovals', 0 ],
 [ 'owner', 0 ],
 [ 'panel', 0 ],
 [ 'paper', 0 ],
 [ 'party', 0 ],
 [ 'peace', 0 ],
 [ 'peppy', 0 ],
 [ 'peter', 0 ],
 [ 'phase', 0 ],
 [ 'phone', 0 ],
 [ 'piano', 0 ],
 [ 'piece', 0 ],
 [ 'pilot', 0 ],
 [ 'pious', 0 ],
 [ 'pique', 0 ],
 [ 'pitch', 0 ],
 [ 'pizza', 0 ],
 [ 'place', 0 ],
 [ 'plain', 0 ],
 [ 'plane', 0 ],
 [ 'plant', 0 ],
 [ 'plate', 0 ],
 [ 'plonk', 0 ],
 [ 'plumb', 0 ],
 [ 'plush', 0 ],
 [ 'point', 0 ],
 [ 'poise', 0 ],
 [ 'pound', 0 ],
 [ 'power', 0 ],
 [ 'press', 0 ],
 [ 'price', 0 ],
 [ 'pride', 0 ],
 [ 'prime', 0 ],
 [ 'prior', 0 ],
 [ 'prize', 0 ],
 [ 'proof', 0 ],
 [ 'proud', 0 ],
 [ 'prove', 0 ],
 [ 'quail', 0 ],
 [ 'quake', 0 ],
 [ 'quart', 0 ],
 [ 'queen', 0 ],
 [ 'queer', 0 ],
 [ 'quell', 0 ],
 [ 'quick', 0 ],
 [ 'quiet', 0 ],
 [ 'quill', 0 ],
 [ 'quint', 0 ],
 [ 'quirk', 0 ],
 [ 'quite', 0 ],
 [ 'radio', 0 ],
 [ 'raise', 0 ],
 [ 'ramen', 0 ],
 [ 'range', 0 ],
 [ 'rapid', 0 ],
 [ 'ratio', 0 ],
 [ 'ravel', 0 ],
 [ 'reach', 0 ],
 [ 'ready', 0 ],
 [ 'redly', 0 ],
 [ 'reedy', 0 ],
 [ 'refer', 0 ],
 [ 'relax', 0 ],
 [ 'reply', 0 ],
 [ 'right', 0 ],
 [ 'river', 0 ],
 [ 'roman', 0 ],
 [ 'rough', 0 ],
 [ 'round', 0 ],
 [ 'route', 0 ],
 [ 'royal', 0 ],
 [ 'ruddy', 0 ],
 [ 'rugby', 0 ],
 [ 'runic', 0 ],
 [ 'rural', 0 ],
 [ 'sable', 0 ],
 [ 'sadly', 0 ],
 [ 'salad', 0 ],
 [ 'sauce', 0 ],
 [ 'scale', 0 ],
 [ 'scene', 0 ],
 [ 'scope', 0 ],
 [ 'score', 0 ],
 [ 'secus', 0 ],
 [ 'selly', 0 ],
 [ 'sense', 0 ],
 [ 'serve', 0 ],
 [ 'shall', 0 ],
 [ 'shape', 0 ],
 [ 'share', 0 ],
 [ 'sharp', 0 ],
 [ 'sheep', 0 ],
 [ 'sheer', 0 ],
 [ 'sheet', 0 ],
 [ 'shift', 0 ],
 [ 'shily', 0 ],
 [ 'shirt', 0 ],
 [ 'shock', 0 ],
 [ 'shoes', 0 ],
 [ 'shoot', 0 ],
 [ 'short', 0 ],
 [ 'shyly', 0 ],
 [ 'sight', 0 ],
 [ 'silly', 0 ],
 [ 'simon', 0 ],
 [ 'since', 0 ],
 [ 'sixth', 0 ],
 [ 'skill', 0 ],
 [ 'skoal', 0 ],
 [ 'sleek', 0 ],
 [ 'sleep', 0 ],
 [ 'slyly', 0 ],
 [ 'small', 0 ],
 [ 'smart', 0 ],
 [ 'smile', 0 ],
 [ 'smith', 0 ],
 [ 'smoke', 0 ],
 [ 'snack', 0 ],
 [ 'snake', 0 ],
 [ 'sniff', 0 ],
 [ 'so-so', 0 ],
 [ 'solid', 0 ],
 [ 'solve', 0 ],
 [ 'sooey', 0 ],
 [ 'sorry', 0 ],
 [ 'sound', 0 ],
 [ 'south', 0 ],
 [ 'space', 0 ],
 [ 'spang', 0 ],
 [ 'spare', 0 ],
 [ 'speak', 0 ],
 [ 'speed', 0 ],
 [ 'spend', 0 ],
 [ 'spice', 0 ],
 [ 'spicy', 0 ],
 [ 'spite', 0 ],
 [ 'split', 0 ],
 [ 'spoon', 0 ],
 [ 'sport', 0 ],
 [ 'squad', 0 ],
 [ 'staff', 0 ],
 [ 'stage', 0 ],
 [ 'stand', 0 ],
 [ 'stark', 0 ],
 [ 'start', 0 ],
 [ 'state', 0 ],
 [ 'steam', 0 ],
 [ 'steel', 0 ],
 [ 'steep', 0 ],
 [ 'stick', 0 ],
 [ 'still', 0 ],
 [ 'stilt', 0 ],
 [ 'stock', 0 ],
 [ 'stone', 0 ],
 [ 'store', 0 ],
 [ 'storm', 0 ],
 [ 'stour', 0 ],
 [ 'study', 0 ],
 [ 'stuff', 0 ],
 [ 'style', 0 ],
 [ 'sugar', 0 ],
 [ 'super', 0 ],
 [ 'swath', 0 ],
 [ 'sweet', 0 ],
 [ 'swirl', 0 ],
 [ 'table', 0 ],
 [ 'tally', 0 ],
 [ 'tanto', 0 ],
 [ 'taste', 0 ],
 [ 'teach', 0 ],
 [ 'terry', 0 ],
 [ 'thank', 0 ],
 [ 'theme', 0 ],
 [ 'there', 0 ],
 [ 'thiam', 0 ],
 [ 'thick', 0 ],
 [ 'thing', 0 ],
 [ 'think', 0 ],
 [ 'third', 0 ],
 [ 'throw', 0 ],
 [ 'thwap', 0 ],
 [ 'tiger', 0 ],
 [ 'tight', 0 ],
 [ 'title', 0 ],
 [ 'toast', 0 ],
 [ 'today', 0 ],
 [ 'tomoz', 0 ],
 [ 'tonic', 0 ],
 [ 'total', 0 ],
 [ 'touch', 0 ],
 [ 'tough', 0 ],
 [ 'tower', 0 ],
 [ 'track', 0 ],
 [ 'trade', 0 ],
 [ 'train', 0 ],
 [ 'treat', 0 ],
 [ 'trend', 0 ],
 [ 'triad', 0 ],
 [ 'trial', 0 ],
 [ 'truly', 0 ],
 [ 'trust', 0 ],
 [ 'truth', 0 ],
 [ 'tryst', 0 ],
 [ 'tweak', 0 ],
 [ 'twice', 0 ],
 [ 'uncle', 0 ],
 [ 'under', 0 ],
 [ 'union', 0 ],
 [ 'unity', 0 ],
 [ 'until', 0 ],
 [ 'upper', 0 ],
 [ 'upset', 0 ],
 [ 'urate', 0 ],
 [ 'urban', 0 ],
 [ 'usual', 0 ],
 [ 'utter', 0 ],
 [ 'vague', 0 ],
 [ 'valid', 0 ],
 [ 'value', 0 ],
 [ 'verry', 0 ],
 [ 'video', 0 ],
 [ 'viola', 0 ],
 [ 'visit', 0 ],
 [ 'vital', 0 ],
 [ 'vivat', 0 ],
 [ 'voice', 0 ],
 [ 'wacko', 0 ],
 [ 'wahey', 0 ],
 [ 'wanly', 0 ],
 [ 'waste', 0 ],
 [ 'watch', 0 ],
 [ 'water', 0 ],
 [ 'waxen', 0 ],
 [ 'wetly', 0 ],
 [ 'whale', 0 ],
 [ 'wheel', 0 ],
 [ 'where', 0 ],
 [ 'which', 0 ],
 [ 'while', 0 ],
 [ 'white', 0 ],
 [ 'whole', 0 ],
 [ 'whose', 0 ],
 [ 'whoso', 0 ],
 [ 'wilma', 0 ],
 [ 'wirra', 0 ],
 [ 'woman', 0 ],
 [ 'woops', 0 ],
 [ 'world', 0 ],
 [ 'worry', 0 ],
 [ 'would', 0 ],
 [ 'wowie', 0 ],
 [ 'write', 0 ],
 [ 'wrong', 0 ],
 [ 'wryly', 0 ],
 [ 'yecch', 0 ],
 [ 'yeeha', 0 ],
 [ 'yeesh', 0 ],
 [ 'young', 0 ],
 [ 'yours', 0 ],
 [ 'youth', 0 ],
 [ 'yowch', 0 ],
 [ 'zebra', 0 ],
 [ 'zowie', 0 ],
];

var WordCount = Words.length;

function cmprec(a,b)
{
	return parseFloat(a[1]) - parseFloat(b[1]);
}

// found logic on https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript
// my idea to seed with time.
function SineRandom() 
{
    var x = Math.sin(SineSeed++) * 100.0;
    return x - Math.floor(x);
}

function SendWord ( Word )
{
	Word = Word.toUpperCase();
	for ( var ndx = 0; ndx < Word.length; ndx++ )
	{
		Letter = Word[ndx];
		for ( var xc = 0; xc < CodeBook.length; xc++ )
		{
			if ( CodeBook[xc][0] != Letter )
			{
				continue;
			}

			for ( var xs = 0; xs < CodeBook[xc][1].length; xs++ )
			{
				if ( CodeBook[xc][1][xs] == '.' )
				{
					(new SoundPlayer(audio)).play(frequency, 1.0, type, when).stop(when+DotMS/1000.0);
					when += (DotMS+IntraMS)/1000.0;
				}
				else
				{
					(new SoundPlayer(audio)).play(frequency, 1.0, type, when).stop(when+DashMS/1000.0);
					when += (DashMS+IntraMS)/1000.0;
				}
			}

			break;
		}
		when += (Farnsworth * InterMS/1000.0);
	}
	when += WordMS/1000.0;
}

