//     Morse Code Practice
// 
//     Copyright (C)  2024 Tom Stevelt
// 
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU Affero General Public License as
//     published by the Free Software Foundation, either version 3 of the
//     License, or (at your option) any later version.
// 
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU Affero General Public License for more details.
// 
//     You should have received a copy of the GNU Affero General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.

var SpeedWPM = 5;
var DotMS = 100;
var DashMS = 3 * DotMS;
var InterMS = 3 * DotMS;
var IntraMS = DotMS;
var WordMS = 7 * DotMS;
var SineSeed = 0.0;
var ErrorCount = 0;
var TotalCount = 0;
var audio;
var audioCtx;
var oscillator;
var biquadFilter;
var gainNode;
var type = 'sine';
var frequency = 440;
var when = 1.0;

function cmprec(a,b)
{
	return parseFloat(a[1]) - parseFloat(b[1]);
}

// found logic on https://stackoverflow.com/questions/521295/seeding-the-random-number-generator-in-javascript
// my idea to seed with time.
function SineRandom() 
{
    var x = Math.sin(SineSeed++) * 100.0;
    return x - Math.floor(x);
}

function SendWord ( Word )
{
	Word = Word.toUpperCase();
	for ( var ndx = 0; ndx < Word.length; ndx++ )
	{
		Letter = Word[ndx];
		for ( var xc = 0; xc < CodeBook.length; xc++ )
		{
			if ( CodeBook[xc][0] != Letter )
			{
				continue;
			}

			for ( var xs = 0; xs < CodeBook[xc][1].length; xs++ )
			{
				if ( CodeBook[xc][1][xs] == '.' )
				{
					(new SoundPlayer(audio)).play(frequency, 1.0, type, when).stop(when+DotMS/1000.0);
					when += (DotMS+IntraMS)/1000.0;
				}
				else
				{
					(new SoundPlayer(audio)).play(frequency, 1.0, type, when).stop(when+DashMS/1000.0);
					when += (DashMS+IntraMS)/1000.0;
				}
			}

			break;
		}
		when += (Farnsworth * InterMS/1000.0);
	}
	when += WordMS/1000.0;
}

var Letters = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.', ',', '/', '?', '@' ];

var Koch = [ 'k', 'm', 'u', 'r', 'e', 's', 'n', 'a', 'p', 't', 'l', 'w', 'i', '.', 'j', 'z', '=', 'f', 'o', 'y', ',', 'v', 'g', '5', '/', 'q', '9', '2', 'h', '3', '8', 'b', '1', 'c', '?', '4', '7',  'd', '6', '0', 'x' ];

var CodeBook = [
//  [ '!','-.-.--', 0 ],
//  [ '$','...-..-', 0 ],
//  [ '&','.-...', 0 ],
//  [ '&quot;','.-..-.', 0 ],
//  [ ''','.----.', 0 ],
//  [ '(','-.--.', 0 ],
//  [ ')','-.--.-', 0 ],
//  [ '+','.-.-.', 0 ],
//  [ '-','-....-', 0 ],
//  [ ':','---...', 0 ],
//  [ ';','-.-.-.', 0 ],
//  [ '_','..--.-', 0 ],
//  [ '|','--...-', 0 ],

  [ ',','--..--', 0 ], // comma
  [ '.','.-.-.-', 0 ], // period
  [ '/','-..-.', 0 ],  // slash
  [ '0','-----', 0 ],
  [ '1','.----', 0 ],
  [ '2','..---', 0 ],
  [ '3','...--', 0 ],
  [ '4','....-', 0 ],
  [ '5','.....', 0 ],
  [ '6','-....', 0 ],
  [ '7','--...', 0 ],
  [ '8','---..', 0 ],
  [ '9','----.', 0 ],
  [ '=','-...-', 0 ], // equals
  [ '?','..--..', 0 ], // question mark
  [ '@','.--.-.', 0 ], // at sign
  [ 'A','.-', 0 ],
  [ 'B','-...', 0 ],
  [ 'C','-.-.', 0 ],
  [ 'D','-..', 0 ],
  [ 'E','.', 0 ],
  [ 'F','..-.', 0 ],
  [ 'G','--.', 0 ],
  [ 'H','....', 0 ],
  [ 'I','..', 0 ],
  [ 'J','.---', 0 ],
  [ 'K','-.-', 0 ],
  [ 'L','.-..', 0 ],
  [ 'M','--', 0 ],
  [ 'N','-.', 0 ],
  [ 'O','---', 0 ],
  [ 'P','.--.', 0 ],
  [ 'Q','--.-', 0 ],
  [ 'R','.-.', 0 ],
  [ 'S','...', 0 ],
  [ 'T','-', 0 ],
  [ 'U','..-', 0 ],
  [ 'V','...-', 0 ],
  [ 'W','.--', 0 ],
  [ 'X','-..-', 0 ],
  [ 'Y','-.--', 0 ],
  [ 'Z','--..', 0 ]
];

var Prosigns = [
 [ 'AR', '.-.-.', 'End of transmission' ],
 [ 'AS', '.-...', 'Wait' ],
 [ 'BK', '-...-.-', 'Invite receiving station to transmit' ],
 [ 'BT', '-...-', 'Pause or Break for text' ],
 [ 'CL', '-.-..-..', 'Going off the air' ],
 [ 'CQ', '-.-.--.-', 'Calling any amateur radio station' ],
 [ 'K', '-.-', 'Invite any station to transmit' ],
 [ 'KA', '-.-.-', 'Beginning of message' ],
 [ 'KN', '-.--.', 'Invite a specific station to transmit' ],
 [ 'R', '.-.', 'All received or OK' ],
 [ 'SK', '...-.-', 'End of contact' ],
 [ 'SOS', '...---...', 'Save Our Ship' ],
 [ 'VE', '...-.', 'Understood' ],
];

var ProsignCount = Prosigns.length;

var Words = [
 [ 'aargh', 0 ],
 [ 'aback', 0 ],
 [ 'abaft', 0 ],
 [ 'aboon', 0 ],
 [ 'about', 0 ],
 [ 'above', 0 ],
 [ 'abuse', 0 ],
 [ 'abyss', 0 ],
 [ 'accel', 0 ],
 [ 'acute', 0 ],
 [ 'adieu', 0 ],
 [ 'adios', 0 ],
 [ 'admit', 0 ],
 [ 'adopt', 0 ],
 [ 'adore', 0 ],
 [ 'adown', 0 ],
 [ 'adult', 0 ],
 [ 'afoot', 0 ],
 [ 'afore', 0 ],
 [ 'afoul', 0 ],
 [ 'after', 0 ],
 [ 'again', 0 ],
 [ 'agape', 0 ],
 [ 'agent', 0 ],
 [ 'agogo', 0 ],
 [ 'agone', 0 ],
 [ 'agree', 0 ],
 [ 'ahead', 0 ],
 [ 'ahull', 0 ],
 [ 'alack', 0 ],
 [ 'alife', 0 ],
 [ 'alike', 0 ],
 [ 'alive', 0 ],
 [ 'allow', 0 ],
 [ 'aloft', 0 ],
 [ 'aloha', 0 ],
 [ 'alone', 0 ],
 [ 'along', 0 ],
 [ 'aloof', 0 ],
 [ 'aloud', 0 ],
 [ 'alter', 0 ],
 [ 'amiss', 0 ],
 [ 'among', 0 ],
 [ 'ample', 0 ],
 [ 'amply', 0 ],
 [ 'anger', 0 ],
 [ 'angry', 0 ],
 [ 'ankle', 0 ],
 [ 'apace', 0 ],
 [ 'apart', 0 ],
 [ 'apple', 0 ],
 [ 'apply', 0 ],
 [ 'aptly', 0 ],
 [ 'arear', 0 ],
 [ 'argue', 0 ],
 [ 'arise', 0 ],
 [ 'aroma', 0 ],
 [ 'aside', 0 ],
 [ 'askew', 0 ],
 [ 'audio', 0 ],
 [ 'audit', 0 ],
 [ 'aural', 0 ],
 [ 'avoid', 0 ],
 [ 'award', 0 ],
 [ 'aware', 0 ],
 [ 'awful', 0 ],
 [ 'badly', 0 ],
 [ 'bally', 0 ],
 [ 'basic', 0 ],
 [ 'basis', 0 ],
 [ 'basta', 0 ],
 [ 'beach', 0 ],
 [ 'begad', 0 ],
 [ 'began', 0 ],
 [ 'begin', 0 ],
 [ 'below', 0 ],
 [ 'birth', 0 ],
 [ 'black', 0 ],
 [ 'blame', 0 ],
 [ 'bless', 0 ],
 [ 'blind', 0 ],
 [ 'block', 0 ],
 [ 'blood', 0 ],
 [ 'blunt', 0 ],
 [ 'board', 0 ],
 [ 'braid', 0 ],
 [ 'brain', 0 ],
 [ 'brave', 0 ],
 [ 'bravo', 0 ],
 [ 'bread', 0 ],
 [ 'break', 0 ],
 [ 'brick', 0 ],
 [ 'brief', 0 ],
 [ 'bring', 0 ],
 [ 'brisk', 0 ],
 [ 'broad', 0 ],
 [ 'brown', 0 ],
 [ 'brush', 0 ],
 [ 'build', 0 ],
 [ 'bumpy', 0 ],
 [ 'burst', 0 ],
 [ 'buyer', 0 ],
 [ 'canny', 0 ],
 [ 'carry', 0 ],
 [ 'catch', 0 ],
 [ 'cause', 0 ],
 [ 'chain', 0 ],
 [ 'chair', 0 ],
 [ 'charm', 0 ],
 [ 'cheap', 0 ],
 [ 'check', 0 ],
 [ 'chest', 0 ],
 [ 'chief', 0 ],
 [ 'child', 0 ],
 [ 'china', 0 ],
 [ 'chive', 0 ],
 [ 'chord', 0 ],
 [ 'circa', 0 ],
 [ 'civil', 0 ],
 [ 'claim', 0 ],
 [ 'clasp', 0 ],
 [ 'class', 0 ],
 [ 'clean', 0 ],
 [ 'clear', 0 ],
 [ 'click', 0 ],
 [ 'climb', 0 ],
 [ 'clock', 0 ],
 [ 'close', 0 ],
 [ 'cloud', 0 ],
 [ 'coach', 0 ],
 [ 'coast', 0 ],
 [ 'count', 0 ],
 [ 'court', 0 ],
 [ 'cover', 0 ],
 [ 'coyly', 0 ],
 [ 'crave', 0 ],
 [ 'crazy', 0 ],
 [ 'cream', 0 ],
 [ 'crest', 0 ],
 [ 'crime', 0 ],
 [ 'cross', 0 ],
 [ 'crowd', 0 ],
 [ 'crown', 0 ],
 [ 'cumin', 0 ],
 [ 'cycle', 0 ],
 [ 'daily', 0 ],
 [ 'damme', 0 ],
 [ 'dance', 0 ],
 [ 'death', 0 ],
 [ 'depth', 0 ],
 [ 'diary', 0 ],
 [ 'dimly', 0 ],
 [ 'dirty', 0 ],
 [ 'ditto', 0 ],
 [ 'doubt', 0 ],
 [ 'draft', 0 ],
 [ 'drama', 0 ],
 [ 'drape', 0 ],
 [ 'dream', 0 ],
 [ 'dregs', 0 ],
 [ 'dress', 0 ],
 [ 'drink', 0 ],
 [ 'drive', 0 ],
 [ 'dryly', 0 ],
 [ 'dully', 0 ],
 [ 'dumpy', 0 ],
 [ 'dusky', 0 ],
 [ 'dwell', 0 ],
 [ 'early', 0 ],
 [ 'earth', 0 ],
 [ 'elite', 0 ],
 [ 'ember', 0 ],
 [ 'empty', 0 ],
 [ 'enact', 0 ],
 [ 'enemy', 0 ],
 [ 'enjoy', 0 ],
 [ 'enter', 0 ],
 [ 'entry', 0 ],
 [ 'equal', 0 ],
 [ 'error', 0 ],
 [ 'evade', 0 ],
 [ 'event', 0 ],
 [ 'evoke', 0 ],
 [ 'exact', 0 ],
 [ 'exist', 0 ],
 [ 'extra', 0 ],
 [ 'fable', 0 ],
 [ 'faint', 0 ],
 [ 'faith', 0 ],
 [ 'false', 0 ],
 [ 'fatly', 0 ],
 [ 'fault', 0 ],
 [ 'feyly', 0 ],
 [ 'field', 0 ],
 [ 'fifth', 0 ],
 [ 'fight', 0 ],
 [ 'final', 0 ],
 [ 'first', 0 ],
 [ 'fitly', 0 ],
 [ 'flair', 0 ],
 [ 'floor', 0 ],
 [ 'fluke', 0 ],
 [ 'flute', 0 ],
 [ 'focus', 0 ],
 [ 'folly', 0 ],
 [ 'force', 0 ],
 [ 'forte', 0 ],
 [ 'forth', 0 ],
 [ 'frame', 0 ],
 [ 'frank', 0 ],
 [ 'fresh', 0 ],
 [ 'frick', 0 ],
 [ 'front', 0 ],
 [ 'fruit', 0 ],
 [ 'fully', 0 ],
 [ 'funny', 0 ],
 [ 'gaily', 0 ],
 [ 'gauze', 0 ],
 [ 'gayly', 0 ],
 [ 'ghost', 0 ],
 [ 'giant', 0 ],
 [ 'giddy', 0 ],
 [ 'glass', 0 ],
 [ 'gloom', 0 ],
 [ 'godly', 0 ],
 [ 'golly', 0 ],
 [ 'gorge', 0 ],
 [ 'grand', 0 ],
 [ 'grant', 0 ],
 [ 'grape', 0 ],
 [ 'grasp', 0 ],
 [ 'grass', 0 ],
 [ 'gratz', 0 ],
 [ 'great', 0 ],
 [ 'green', 0 ],
 [ 'gross', 0 ],
 [ 'group', 0 ],
 [ 'guess', 0 ],
 [ 'guide', 0 ],
 [ 'gusty', 0 ],
 [ 'hallo', 0 ],
 [ 'haply', 0 ],
 [ 'happy', 0 ],
 [ 'harsh', 0 ],
 [ 'haste', 0 ],
 [ 'havoc', 0 ],
 [ 'heart', 0 ],
 [ 'heavy', 0 ],
 [ 'hella', 0 ],
 [ 'hence', 0 ],
 [ 'henry', 0 ],
 [ 'hilly', 0 ],
 [ 'hippy', 0 ],
 [ 'horse', 0 ],
 [ 'hotel', 0 ],
 [ 'hotly', 0 ],
 [ 'house', 0 ],
 [ 'hovel', 0 ],
 [ 'howay', 0 ],
 [ 'howdy', 0 ],
 [ 'hullo', 0 ],
 [ 'human', 0 ],
 [ 'hunch', 0 ],
 [ 'huzza', 0 ],
 [ 'icily', 0 ],
 [ 'ideal', 0 ],
 [ 'image', 0 ],
 [ 'imply', 0 ],
 [ 'index', 0 ],
 [ 'inept', 0 ],
 [ 'inert', 0 ],
 [ 'infra', 0 ],
 [ 'inner', 0 ],
 [ 'input', 0 ],
 [ 'intl.', 0 ],
 [ 'irate', 0 ],
 [ 'issue', 0 ],
 [ 'ivory', 0 ],
 [ 'jaded', 0 ],
 [ 'japan', 0 ],
 [ 'jazzy', 0 ],
 [ 'jesus', 0 ],
 [ 'jildi', 0 ],
 [ 'joint', 0 ],
 [ 'jolly', 0 ],
 [ 'jones', 0 ],
 [ 'joust', 0 ],
 [ 'judge', 0 ],
 [ 'juice', 0 ],
 [ 'jumbo', 0 ],
 [ 'jumpy', 0 ],
 [ 'kapow', 0 ],
 [ 'kinky', 0 ],
 [ 'knack', 0 ],
 [ 'knave', 0 ],
 [ 'knead', 0 ],
 [ 'knife', 0 ],
 [ 'kudos', 0 ],
 [ 'lanky', 0 ],
 [ 'large', 0 ],
 [ 'latch', 0 ],
 [ 'laugh', 0 ],
 [ 'laura', 0 ],
 [ 'laxly', 0 ],
 [ 'layer', 0 ],
 [ 'learn', 0 ],
 [ 'leave', 0 ],
 [ 'legal', 0 ],
 [ 'lento', 0 ],
 [ 'level', 0 ],
 [ 'lewis', 0 ],
 [ 'light', 0 ],
 [ 'limit', 0 ],
 [ 'local', 0 ],
 [ 'lolly', 0 ],
 [ 'loose', 0 ],
 [ 'lordy', 0 ],
 [ 'louie', 0 ],
 [ 'lowly', 0 ],
 [ 'lucky', 0 ],
 [ 'lunch', 0 ],
 [ 'lurid', 0 ],
 [ 'madly', 0 ],
 [ 'magic', 0 ],
 [ 'major', 0 ],
 [ 'march', 0 ],
 [ 'marry', 0 ],
 [ 'match', 0 ],
 [ 'maybe', 0 ],
 [ 'metal', 0 ],
 [ 'minor', 0 ],
 [ 'minus', 0 ],
 [ 'mirth', 0 ],
 [ 'mixed', 0 ],
 [ 'model', 0 ],
 [ 'money', 0 ],
 [ 'month', 0 ],
 [ 'moody', 0 ],
 [ 'moral', 0 ],
 [ 'motor', 0 ],
 [ 'mourn', 0 ],
 [ 'mouth', 0 ],
 [ 'mower', 0 ],
 [ 'muggy', 0 ],
 [ 'music', 0 ],
 [ 'naked', 0 ],
 [ 'nanny', 0 ],
 [ 'nappy', 0 ],
 [ 'nasty', 0 ],
 [ 'naval', 0 ],
 [ 'neath', 0 ],
 [ 'nerve', 0 ],
 [ 'never', 0 ],
 [ 'newly', 0 ],
 [ 'nifty', 0 ],
 [ 'night', 0 ],
 [ 'nobly', 0 ],
 [ 'noise', 0 ],
 [ 'north', 0 ],
 [ 'novel', 0 ],
 [ 'nudge', 0 ],
 [ 'nurse', 0 ],
 [ 'occur', 0 ],
 [ 'oddly', 0 ],
 [ 'offer', 0 ],
 [ 'often', 0 ],
 [ 'olive', 0 ],
 [ 'onset', 0 ],
 [ 'oomph', 0 ],
 [ 'order', 0 ],
 [ 'oread', 0 ],
 [ 'other', 0 ],
 [ 'ought', 0 ],
 [ 'ounce', 0 ],
 [ 'outer', 0 ],
 [ 'ovals', 0 ],
 [ 'owner', 0 ],
 [ 'panel', 0 ],
 [ 'paper', 0 ],
 [ 'party', 0 ],
 [ 'peace', 0 ],
 [ 'peppy', 0 ],
 [ 'peter', 0 ],
 [ 'phase', 0 ],
 [ 'phone', 0 ],
 [ 'piano', 0 ],
 [ 'piece', 0 ],
 [ 'pilot', 0 ],
 [ 'pious', 0 ],
 [ 'pique', 0 ],
 [ 'pitch', 0 ],
 [ 'pizza', 0 ],
 [ 'place', 0 ],
 [ 'plain', 0 ],
 [ 'plane', 0 ],
 [ 'plant', 0 ],
 [ 'plate', 0 ],
 [ 'plonk', 0 ],
 [ 'plumb', 0 ],
 [ 'plush', 0 ],
 [ 'point', 0 ],
 [ 'poise', 0 ],
 [ 'pound', 0 ],
 [ 'power', 0 ],
 [ 'press', 0 ],
 [ 'price', 0 ],
 [ 'pride', 0 ],
 [ 'prime', 0 ],
 [ 'prior', 0 ],
 [ 'prize', 0 ],
 [ 'proof', 0 ],
 [ 'proud', 0 ],
 [ 'prove', 0 ],
 [ 'quail', 0 ],
 [ 'quake', 0 ],
 [ 'quart', 0 ],
 [ 'queen', 0 ],
 [ 'queer', 0 ],
 [ 'quell', 0 ],
 [ 'quick', 0 ],
 [ 'quiet', 0 ],
 [ 'quill', 0 ],
 [ 'quint', 0 ],
 [ 'quirk', 0 ],
 [ 'quite', 0 ],
 [ 'radio', 0 ],
 [ 'raise', 0 ],
 [ 'ramen', 0 ],
 [ 'range', 0 ],
 [ 'rapid', 0 ],
 [ 'ratio', 0 ],
 [ 'ravel', 0 ],
 [ 'reach', 0 ],
 [ 'ready', 0 ],
 [ 'redly', 0 ],
 [ 'reedy', 0 ],
 [ 'refer', 0 ],
 [ 'relax', 0 ],
 [ 'reply', 0 ],
 [ 'right', 0 ],
 [ 'river', 0 ],
 [ 'roman', 0 ],
 [ 'rough', 0 ],
 [ 'round', 0 ],
 [ 'route', 0 ],
 [ 'royal', 0 ],
 [ 'ruddy', 0 ],
 [ 'rugby', 0 ],
 [ 'runic', 0 ],
 [ 'rural', 0 ],
 [ 'sable', 0 ],
 [ 'sadly', 0 ],
 [ 'salad', 0 ],
 [ 'sauce', 0 ],
 [ 'scale', 0 ],
 [ 'scene', 0 ],
 [ 'scope', 0 ],
 [ 'score', 0 ],
 [ 'secus', 0 ],
 [ 'selly', 0 ],
 [ 'sense', 0 ],
 [ 'serve', 0 ],
 [ 'shall', 0 ],
 [ 'shape', 0 ],
 [ 'share', 0 ],
 [ 'sharp', 0 ],
 [ 'sheep', 0 ],
 [ 'sheer', 0 ],
 [ 'sheet', 0 ],
 [ 'shift', 0 ],
 [ 'shily', 0 ],
 [ 'shirt', 0 ],
 [ 'shock', 0 ],
 [ 'shoes', 0 ],
 [ 'shoot', 0 ],
 [ 'short', 0 ],
 [ 'shyly', 0 ],
 [ 'sight', 0 ],
 [ 'silly', 0 ],
 [ 'simon', 0 ],
 [ 'since', 0 ],
 [ 'sixth', 0 ],
 [ 'skill', 0 ],
 [ 'skoal', 0 ],
 [ 'sleek', 0 ],
 [ 'sleep', 0 ],
 [ 'slyly', 0 ],
 [ 'small', 0 ],
 [ 'smart', 0 ],
 [ 'smile', 0 ],
 [ 'smith', 0 ],
 [ 'smoke', 0 ],
 [ 'snack', 0 ],
 [ 'snake', 0 ],
 [ 'sniff', 0 ],
 [ 'solid', 0 ],
 [ 'solve', 0 ],
 [ 'sooey', 0 ],
 [ 'sorry', 0 ],
 [ 'sound', 0 ],
 [ 'south', 0 ],
 [ 'space', 0 ],
 [ 'spang', 0 ],
 [ 'spare', 0 ],
 [ 'speak', 0 ],
 [ 'speed', 0 ],
 [ 'spend', 0 ],
 [ 'spice', 0 ],
 [ 'spicy', 0 ],
 [ 'spite', 0 ],
 [ 'split', 0 ],
 [ 'spoon', 0 ],
 [ 'sport', 0 ],
 [ 'squad', 0 ],
 [ 'staff', 0 ],
 [ 'stage', 0 ],
 [ 'stand', 0 ],
 [ 'stark', 0 ],
 [ 'start', 0 ],
 [ 'state', 0 ],
 [ 'steam', 0 ],
 [ 'steel', 0 ],
 [ 'steep', 0 ],
 [ 'stick', 0 ],
 [ 'still', 0 ],
 [ 'stilt', 0 ],
 [ 'stock', 0 ],
 [ 'stone', 0 ],
 [ 'store', 0 ],
 [ 'storm', 0 ],
 [ 'stour', 0 ],
 [ 'study', 0 ],
 [ 'stuff', 0 ],
 [ 'style', 0 ],
 [ 'sugar', 0 ],
 [ 'super', 0 ],
 [ 'swath', 0 ],
 [ 'sweet', 0 ],
 [ 'swirl', 0 ],
 [ 'table', 0 ],
 [ 'tally', 0 ],
 [ 'tanto', 0 ],
 [ 'taste', 0 ],
 [ 'teach', 0 ],
 [ 'terry', 0 ],
 [ 'thank', 0 ],
 [ 'theme', 0 ],
 [ 'there', 0 ],
 [ 'thiam', 0 ],
 [ 'thick', 0 ],
 [ 'thing', 0 ],
 [ 'think', 0 ],
 [ 'third', 0 ],
 [ 'throw', 0 ],
 [ 'thwap', 0 ],
 [ 'tiger', 0 ],
 [ 'tight', 0 ],
 [ 'title', 0 ],
 [ 'toast', 0 ],
 [ 'today', 0 ],
 [ 'tomoz', 0 ],
 [ 'tonic', 0 ],
 [ 'total', 0 ],
 [ 'touch', 0 ],
 [ 'tough', 0 ],
 [ 'tower', 0 ],
 [ 'track', 0 ],
 [ 'trade', 0 ],
 [ 'train', 0 ],
 [ 'treat', 0 ],
 [ 'trend', 0 ],
 [ 'triad', 0 ],
 [ 'trial', 0 ],
 [ 'truly', 0 ],
 [ 'trust', 0 ],
 [ 'truth', 0 ],
 [ 'tryst', 0 ],
 [ 'tweak', 0 ],
 [ 'twice', 0 ],
 [ 'uncle', 0 ],
 [ 'under', 0 ],
 [ 'union', 0 ],
 [ 'unity', 0 ],
 [ 'until', 0 ],
 [ 'upper', 0 ],
 [ 'upset', 0 ],
 [ 'urate', 0 ],
 [ 'urban', 0 ],
 [ 'usual', 0 ],
 [ 'utter', 0 ],
 [ 'vague', 0 ],
 [ 'valid', 0 ],
 [ 'value', 0 ],
 [ 'verry', 0 ],
 [ 'video', 0 ],
 [ 'viola', 0 ],
 [ 'visit', 0 ],
 [ 'vital', 0 ],
 [ 'vivat', 0 ],
 [ 'voice', 0 ],
 [ 'wacko', 0 ],
 [ 'wahey', 0 ],
 [ 'wanly', 0 ],
 [ 'waste', 0 ],
 [ 'watch', 0 ],
 [ 'water', 0 ],
 [ 'waxen', 0 ],
 [ 'wetly', 0 ],
 [ 'whale', 0 ],
 [ 'wheel', 0 ],
 [ 'where', 0 ],
 [ 'which', 0 ],
 [ 'while', 0 ],
 [ 'white', 0 ],
 [ 'whole', 0 ],
 [ 'whose', 0 ],
 [ 'whoso', 0 ],
 [ 'wilma', 0 ],
 [ 'wirra', 0 ],
 [ 'woman', 0 ],
 [ 'woops', 0 ],
 [ 'world', 0 ],
 [ 'worry', 0 ],
 [ 'would', 0 ],
 [ 'wowie', 0 ],
 [ 'write', 0 ],
 [ 'wrong', 0 ],
 [ 'wryly', 0 ],
 [ 'yecch', 0 ],
 [ 'yeeha', 0 ],
 [ 'yeesh', 0 ],
 [ 'young', 0 ],
 [ 'yours', 0 ],
 [ 'youth', 0 ],
 [ 'yowch', 0 ],
 [ 'zebra', 0 ],
 [ 'zowie', 0 ],
];

var Variable = [
 [ 'a', 0 ],
 [ 'about', 0 ],
 [ 'access', 0 ],
 [ 'according', 0 ],
 [ 'account', 0 ],
 [ 'act', 0 ],
 [ 'action', 0 ],
 [ 'activity', 0 ],
 [ 'ad', 0 ],
 [ 'add', 0 ],
 [ 'addition', 0 ],
 [ 'address', 0 ],
 [ 'advanced', 0 ],
 [ 'advertise', 0 ],
 [ 'after', 0 ],
 [ 'again', 0 ],
 [ 'against', 0 ],
 [ 'age', 0 ],
 [ 'ago', 0 ],
 [ 'agreement', 0 ],
 [ 'air', 0 ],
 [ 'all', 0 ],
 [ 'already', 0 ],
 [ 'also', 0 ],
 [ 'although', 0 ],
 [ 'always', 0 ],
 [ 'AM', 0 ],
 [ 'america', 0 ],
 [ 'american', 0 ],
 [ 'an', 0 ],
 [ 'analysis', 0 ],
 [ 'and', 0 ],
 [ 'another', 0 ],
 [ 'any', 0 ],
 [ 'anything', 0 ],
 [ 'apr', 0 ],
 [ 'april', 0 ],
 [ 'archive', 0 ],
 [ 'archives', 0 ],
 [ 'are', 0 ],
 [ 'area', 0 ],
 [ 'around', 0 ],
 [ 'art', 0 ],
 [ 'article', 0 ],
 [ 'articles', 0 ],
 [ 'as', 0 ],
 [ 'ask', 0 ],
 [ 'at', 0 ],
 [ 'attention', 0 ],
 [ 'aug', 0 ],
 [ 'august', 0 ],
 [ 'australia', 0 ],
 [ 'author', 0 ],
 [ 'authority', 0 ],
 [ 'available', 0 ],
 [ 'average', 0 ],
 [ 'back', 0 ],
 [ 'bad', 0 ],
 [ 'based', 0 ],
 [ 'be', 0 ],
 [ 'beautiful', 0 ],
 [ 'because', 0 ],
 [ 'become', 0 ],
 [ 'been', 0 ],
 [ 'before', 0 ],
 [ 'beginning', 0 ],
 [ 'being', 0 ],
 [ 'below', 0 ],
 [ 'benefits', 0 ],
 [ 'best', 0 ],
 [ 'better', 0 ],
 [ 'between', 0 ],
 [ 'big', 0 ],
 [ 'black', 0 ],
 [ 'board', 0 ],
 [ 'book', 0 ],
 [ 'books', 0 ],
 [ 'both', 0 ],
 [ 'box', 0 ],
 [ 'browse', 0 ],
 [ 'building', 0 ],
 [ 'business', 0 ],
 [ 'but', 0 ],
 [ 'buy', 0 ],
 [ 'by', 0 ],
 [ 'calendar', 0 ],
 [ 'called', 0 ],
 [ 'can', 0 ],
 [ 'canada', 0 ],
 [ 'car', 0 ],
 [ 'care', 0 ],
 [ 'case', 0 ],
 [ 'category', 0 ],
 [ 'CC', 0 ],
 [ 'center', 0 ],
 [ 'central', 0 ],
 [ 'change', 0 ],
 [ 'changes', 0 ],
 [ 'character', 0 ],
 [ 'check', 0 ],
 [ 'children', 0 ],
 [ 'christian', 0 ],
 [ 'christmas', 0 ],
 [ 'city', 0 ],
 [ 'class', 0 ],
 [ 'click', 0 ],
 [ 'clothing', 0 ],
 [ 'cm', 0 ],
 [ 'code', 0 ],
 [ 'college', 0 ],
 [ 'comment', 0 ],
 [ 'comments', 0 ],
 [ 'committee', 0 ],
 [ 'common', 0 ],
 [ 'community', 0 ],
 [ 'companies', 0 ],
 [ 'company', 0 ],
 [ 'compare', 0 ],
 [ 'complete', 0 ],
 [ 'completed', 0 ],
 [ 'component', 0 ],
 [ 'computer', 0 ],
 [ 'computers', 0 ],
 [ 'condition', 0 ],
 [ 'contact', 0 ],
 [ 'content', 0 ],
 [ 'contents', 0 ],
 [ 'continue', 0 ],
 [ 'continued', 0 ],
 [ 'control', 0 ],
 [ 'copyright', 0 ],
 [ 'corporate', 0 ],
 [ 'could', 0 ],
 [ 'council', 0 ],
 [ 'countries', 0 ],
 [ 'country', 0 ],
 [ 'county', 0 ],
 [ 'course', 0 ],
 [ 'create', 0 ],
 [ 'credit', 0 ],
 [ 'current', 0 ],
 [ 'currently', 0 ],
 [ 'customer', 0 ],
 [ 'customers', 0 ],
 [ 'data', 0 ],
 [ 'database', 0 ],
 [ 'date', 0 ],
 [ 'day', 0 ],
 [ 'days', 0 ],
 [ 'dec', 0 ],
 [ 'december', 0 ],
 [ 'decision', 0 ],
 [ 'delivery', 0 ],
 [ 'described', 0 ],
 [ 'design', 0 ],
 [ 'designed', 0 ],
 [ 'details', 0 ],
 [ 'determine', 0 ],
 [ 'developed', 0 ],
 [ 'did', 0 ],
 [ 'different', 0 ],
 [ 'difficult', 0 ],
 [ 'digital', 0 ],
 [ 'direc', 0 ],
 [ 'director', 0 ],
 [ 'directory', 0 ],
 [ 'discount', 0 ],
 [ 'display', 0 ],
 [ 'district', 0 ],
 [ 'division', 0 ],
 [ 'DJ', 0 ],
 [ 'do', 0 ],
 [ 'document', 0 ],
 [ 'documents', 0 ],
 [ 'does', 0 ],
 [ 'down', 0 ],
 [ 'download', 0 ],
 [ 'downloads', 0 ],
 [ 'Dr', 0 ],
 [ 'due', 0 ],
 [ 'during', 0 ],
 [ 'each', 0 ],
 [ 'economic', 0 ],
 [ 'edition', 0 ],
 [ 'education', 0 ],
 [ 'effective', 0 ],
 [ 'EG', 0 ],
 [ 'email', 0 ],
 [ 'emergency', 0 ],
 [ 'employees', 0 ],
 [ 'end', 0 ],
 [ 'energy', 0 ],
 [ 'english', 0 ],
 [ 'equipment', 0 ],
 [ 'estate', 0 ],
 [ 'european', 0 ],
 [ 'even', 0 ],
 [ 'events', 0 ],
 [ 'every', 0 ],
 [ 'ex', 0 ],
 [ 'example', 0 ],
 [ 'excellent', 0 ],
 [ 'exchange', 0 ],
 [ 'executive', 0 ],
 [ 'family', 0 ],
 [ 'faq', 0 ],
 [ 'far', 0 ],
 [ 'fax', 0 ],
 [ 'features', 0 ],
 [ 'february', 0 ],
 [ 'federal', 0 ],
 [ 'feedback', 0 ],
 [ 'few', 0 ],
 [ 'file', 0 ],
 [ 'finance', 0 ],
 [ 'financial', 0 ],
 [ 'find', 0 ],
 [ 'first', 0 ],
 [ 'following', 0 ],
 [ 'for', 0 ],
 [ 'form', 0 ],
 [ 'format', 0 ],
 [ 'forum', 0 ],
 [ 'forums', 0 ],
 [ 'found', 0 ],
 [ 'france', 0 ],
 [ 'francisco', 0 ],
 [ 'free', 0 ],
 [ 'friend', 0 ],
 [ 'friends', 0 ],
 [ 'from', 0 ],
 [ 'ft', 0 ],
 [ 'full', 0 ],
 [ 'fun', 0 ],
 [ 'function', 0 ],
 [ 'functions', 0 ],
 [ 'furniture', 0 ],
 [ 'further', 0 ],
 [ 'future', 0 ],
 [ 'galleries', 0 ],
 [ 'gallery', 0 ],
 [ 'game', 0 ],
 [ 'games', 0 ],
 [ 'garden', 0 ],
 [ 'general', 0 ],
 [ 'generally', 0 ],
 [ 'get', 0 ],
 [ 'go', 0 ],
 [ 'god', 0 ],
 [ 'going', 0 ],
 [ 'good', 0 ],
 [ 'got', 0 ],
 [ 'great', 0 ],
 [ 'group', 0 ],
 [ 'groups', 0 ],
 [ 'guarantee', 0 ],
 [ 'guide', 0 ],
 [ 'had', 0 ],
 [ 'hardware', 0 ],
 [ 'has', 0 ],
 [ 'have', 0 ],
 [ 'having', 0 ],
 [ 'he', 0 ],
 [ 'health', 0 ],
 [ 'help', 0 ],
 [ 'her', 0 ],
 [ 'here', 0 ],
 [ 'hi', 0 ],
 [ 'high', 0 ],
 [ 'him', 0 ],
 [ 'his', 0 ],
 [ 'history', 0 ],
 [ 'home', 0 ],
 [ 'hosting', 0 ],
 [ 'hot', 0 ],
 [ 'hotel', 0 ],
 [ 'hotels', 0 ],
 [ 'hours', 0 ],
 [ 'house', 0 ],
 [ 'how', 0 ],
 [ 'however', 0 ],
 [ 'HP', 0 ],
 [ 'hr', 0 ],
 [ 'human', 0 ],
 [ 'I', 0 ],
 [ 'ID', 0 ],
 [ 'ie', 0 ],
 [ 'if', 0 ],
 [ 'image', 0 ],
 [ 'images', 0 ],
 [ 'important', 0 ],
 [ 'in', 0 ],
 [ 'include', 0 ],
 [ 'included', 0 ],
 [ 'includes', 0 ],
 [ 'including', 0 ],
 [ 'increase', 0 ],
 [ 'increased', 0 ],
 [ 'index', 0 ],
 [ 'industry', 0 ],
 [ 'info', 0 ],
 [ 'institute', 0 ],
 [ 'insurance', 0 ],
 [ 'interest', 0 ],
 [ 'interface', 0 ],
 [ 'internet', 0 ],
 [ 'into', 0 ],
 [ 'is', 0 ],
 [ 'island', 0 ],
 [ 'issues', 0 ],
 [ 'it', 0 ],
 [ 'item', 0 ],
 [ 'items', 0 ],
 [ 'its', 0 ],
 [ 'IV', 0 ],
 [ 'jan', 0 ],
 [ 'january', 0 ],
 [ 'job', 0 ],
 [ 'john', 0 ],
 [ 'journal', 0 ],
 [ 'jun', 0 ],
 [ 'just', 0 ],
 [ 'kb', 0 ],
 [ 'key', 0 ],
 [ 'km', 0 ],
 [ 'know', 0 ],
 [ 'knowledge', 0 ],
 [ 'language', 0 ],
 [ 'large', 0 ],
 [ 'last', 0 ],
 [ 'latest', 0 ],
 [ 'law', 0 ],
 [ 'learn', 0 ],
 [ 'learning', 0 ],
 [ 'let', 0 ],
 [ 'level', 0 ],
 [ 'library', 0 ],
 [ 'life', 0 ],
 [ 'like', 0 ],
 [ 'limited', 0 ],
 [ 'line', 0 ],
 [ 'link', 0 ],
 [ 'links', 0 ],
 [ 'list', 0 ],
 [ 'listed', 0 ],
 [ 'listing', 0 ],
 [ 'listings', 0 ],
 [ 'little', 0 ],
 [ 'living', 0 ],
 [ 'local', 0 ],
 [ 'location', 0 ],
 [ 'locations', 0 ],
 [ 'log', 0 ],
 [ 'london', 0 ],
 [ 'long', 0 ],
 [ 'looking', 0 ],
 [ 'lot', 0 ],
 [ 'love', 0 ],
 [ 'low', 0 ],
 [ 'made', 0 ],
 [ 'magazine', 0 ],
 [ 'magazines', 0 ],
 [ 'mail', 0 ],
 [ 'main', 0 ],
 [ 'make', 0 ],
 [ 'making', 0 ],
 [ 'man', 0 ],
 [ 'many', 0 ],
 [ 'map', 0 ],
 [ 'mar', 0 ],
 [ 'march', 0 ],
 [ 'market', 0 ],
 [ 'marketing', 0 ],
 [ 'material', 0 ],
 [ 'materials', 0 ],
 [ 'may', 0 ],
 [ 'media', 0 ],
 [ 'medical', 0 ],
 [ 'meeting', 0 ],
 [ 'member', 0 ],
 [ 'members', 0 ],
 [ 'memory', 0 ],
 [ 'men', 0 ],
 [ 'message', 0 ],
 [ 'messages', 0 ],
 [ 'military', 0 ],
 [ 'million', 0 ],
 [ 'minutes', 0 ],
 [ 'mm', 0 ],
 [ 'mobile', 0 ],
 [ 'model', 0 ],
 [ 'money', 0 ],
 [ 'months', 0 ],
 [ 'more', 0 ],
 [ 'mortgage', 0 ],
 [ 'most', 0 ],
 [ 'movie', 0 ],
 [ 'movies', 0 ],
 [ 'Miss', 0 ],
 [ 'Mr', 0 ],
 [ 'Mrs', 0 ],
 [ 'Ms', 0 ],
 [ 'much', 0 ],
 [ 'music', 0 ],
 [ 'must', 0 ],
 [ 'my', 0 ],
 [ 'name', 0 ],
 [ 'national', 0 ],
 [ 'natural', 0 ],
 [ 'necessary', 0 ],
 [ 'need', 0 ],
 [ 'net', 0 ],
 [ 'network', 0 ],
 [ 'never', 0 ],
 [ 'new', 0 ],
 [ 'news', 0 ],
 [ 'next', 0 ],
 [ 'no', 0 ],
 [ 'non', 0 ],
 [ 'north', 0 ],
 [ 'not', 0 ],
 [ 'notice', 0 ],
 [ 'nov', 0 ],
 [ 'november', 0 ],
 [ 'now', 0 ],
 [ 'number', 0 ],
 [ 'oct', 0 ],
 [ 'october', 0 ],
 [ 'of', 0 ],
 [ 'off', 0 ],
 [ 'offers', 0 ],
 [ 'office', 0 ],
 [ 'official', 0 ],
 [ 'oh', 0 ],
 [ 'oil', 0 ],
 [ 'okay', 0 ],
 [ 'old', 0 ],
 [ 'on', 0 ],
 [ 'one', 0 ],
 [ 'online', 0 ],
 [ 'only', 0 ],
 [ 'open', 0 ],
 [ 'operating', 0 ],
 [ 'operation', 0 ],
 [ 'options', 0 ],
 [ 'or', 0 ],
 [ 'order', 0 ],
 [ 'original', 0 ],
 [ 'OS', 0 ],
 [ 'other', 0 ],
 [ 'others', 0 ],
 [ 'otherwise', 0 ],
 [ 'our', 0 ],
 [ 'out', 0 ],
 [ 'over', 0 ],
 [ 'own', 0 ],
 [ 'Pa', 0 ],
 [ 'page', 0 ],
 [ 'pages', 0 ],
 [ 'part', 0 ],
 [ 'password', 0 ],
 [ 'pay', 0 ],
 [ 'payment', 0 ],
 [ 'PC', 0 ],
 [ 'people', 0 ],
 [ 'per', 0 ],
 [ 'period', 0 ],
 [ 'person', 0 ],
 [ 'personal', 0 ],
 [ 'phone', 0 ],
 [ 'photo', 0 ],
 [ 'photos', 0 ],
 [ 'picture', 0 ],
 [ 'pictures', 0 ],
 [ 'place', 0 ],
 [ 'planning', 0 ],
 [ 'please', 0 ],
 [ 'PM', 0 ],
 [ 'point', 0 ],
 [ 'policies', 0 ],
 [ 'policy', 0 ],
 [ 'political', 0 ],
 [ 'popular', 0 ],
 [ 'position', 0 ],
 [ 'possible', 0 ],
 [ 'post', 0 ],
 [ 'posted', 0 ],
 [ 'posts', 0 ],
 [ 'potential', 0 ],
 [ 'power', 0 ],
 [ 'powered', 0 ],
 [ 'practice', 0 ],
 [ 'present', 0 ],
 [ 'presented', 0 ],
 [ 'president', 0 ],
 [ 'press', 0 ],
 [ 'previous', 0 ],
 [ 'price', 0 ],
 [ 'prices', 0 ],
 [ 'print', 0 ],
 [ 'privacy', 0 ],
 [ 'private', 0 ],
 [ 'pro', 0 ],
 [ 'problem', 0 ],
 [ 'problems', 0 ],
 [ 'process', 0 ],
 [ 'processes', 0 ],
 [ 'product', 0 ],
 [ 'products', 0 ],
 [ 'professor', 0 ],
 [ 'profile', 0 ],
 [ 'program', 0 ],
 [ 'programme', 0 ],
 [ 'programs', 0 ],
 [ 'project', 0 ],
 [ 'projects', 0 ],
 [ 'property', 0 ],
 [ 'provide', 0 ],
 [ 'provided', 0 ],
 [ 'provides', 0 ],
 [ 'providing', 0 ],
 [ 'public', 0 ],
 [ 'published', 0 ],
 [ 'publisher', 0 ],
 [ 'purchase', 0 ],
 [ 'put', 0 ],
 [ 'quality', 0 ],
 [ 'question', 0 ],
 [ 'questions', 0 ],
 [ 'rate', 0 ],
 [ 'rating', 0 ],
 [ 're', 0 ],
 [ 'read', 0 ],
 [ 'real', 0 ],
 [ 'really', 0 ],
 [ 'received', 0 ],
 [ 'recent', 0 ],
 [ 'recommend', 0 ],
 [ 'record', 0 ],
 [ 'records', 0 ],
 [ 'red', 0 ],
 [ 'reference', 0 ],
 [ 'regarding', 0 ],
 [ 'region', 0 ],
 [ 'regional', 0 ],
 [ 'register', 0 ],
 [ 'related', 0 ],
 [ 'relations', 0 ],
 [ 'release', 0 ],
 [ 'remember', 0 ],
 [ 'reply', 0 ],
 [ 'report', 0 ],
 [ 'reports', 0 ],
 [ 'request', 0 ],
 [ 'required', 0 ],
 [ 'research', 0 ],
 [ 'reserved', 0 ],
 [ 'resource', 0 ],
 [ 'resources', 0 ],
 [ 'response', 0 ],
 [ 'result', 0 ],
 [ 'results', 0 ],
 [ 'return', 0 ],
 [ 'review', 0 ],
 [ 'reviews', 0 ],
 [ 'right', 0 ],
 [ 'rights', 0 ],
 [ 'run', 0 ],
 [ 'safety', 0 ],
 [ 'said', 0 ],
 [ 'sales', 0 ],
 [ 'same', 0 ],
 [ 'san', 0 ],
 [ 'satellite', 0 ],
 [ 'say', 0 ],
 [ 'school', 0 ],
 [ 'schools', 0 ],
 [ 'science', 0 ],
 [ 'search', 0 ],
 [ 'second', 0 ],
 [ 'secretary', 0 ],
 [ 'section', 0 ],
 [ 'security', 0 ],
 [ 'see', 0 ],
 [ 'select', 0 ],
 [ 'selection', 0 ],
 [ 'seller', 0 ],
 [ 'send', 0 ],
 [ 'sep', 0 ],
 [ 'september', 0 ],
 [ 'series', 0 ],
 [ 'server', 0 ],
 [ 'service', 0 ],
 [ 'services', 0 ],
 [ 'set', 0 ],
 [ 'several', 0 ],
 [ 'shall', 0 ],
 [ 'she', 0 ],
 [ 'shipping', 0 ],
 [ 'shop', 0 ],
 [ 'shopping', 0 ],
 [ 'should', 0 ],
 [ 'show', 0 ],
 [ 'sign', 0 ],
 [ 'similar', 0 ],
 [ 'since', 0 ],
 [ 'single', 0 ],
 [ 'site', 0 ],
 [ 'sites', 0 ],
 [ 'situation', 0 ],
 [ 'size', 0 ],
 [ 'small', 0 ],
 [ 'so', 0 ],
 [ 'social', 0 ],
 [ 'society', 0 ],
 [ 'software', 0 ],
 [ 'solution', 0 ],
 [ 'solutions', 0 ],
 [ 'some', 0 ],
 [ 'something', 0 ],
 [ 'sometimes', 0 ],
 [ 'source', 0 ],
 [ 'south', 0 ],
 [ 'special', 0 ],
 [ 'specific', 0 ],
 [ 'specified', 0 ],
 [ 'sponsored', 0 ],
 [ 'sports', 0 ],
 [ 'ST', 0 ],
 [ 'staff', 0 ],
 [ 'standard', 0 ],
 [ 'standards', 0 ],
 [ 'start', 0 ],
 [ 'state', 0 ],
 [ 'statement', 0 ],
 [ 'states', 0 ],
 [ 'status', 0 ],
 [ 'still', 0 ],
 [ 'stock', 0 ],
 [ 'store', 0 ],
 [ 'stores', 0 ],
 [ 'stories', 0 ],
 [ 'street', 0 ],
 [ 'structure', 0 ],
 [ 'student', 0 ],
 [ 'students', 0 ],
 [ 'studies', 0 ],
 [ 'study', 0 ],
 [ 'subject', 0 ],
 [ 'submitted', 0 ],
 [ 'subscribe', 0 ],
 [ 'such', 0 ],
 [ 'sun', 0 ],
 [ 'supplies', 0 ],
 [ 'support', 0 ],
 [ 'system', 0 ],
 [ 'systems', 0 ],
 [ 't', 0 ],
 [ 'table', 0 ],
 [ 'take', 0 ],
 [ 'tax', 0 ],
 [ 'technical', 0 ],
 [ 'telephone', 0 ],
 [ 'terms', 0 ],
 [ 'text', 0 ],
 [ 'than', 0 ],
 [ 'that', 0 ],
 [ 'the', 0 ],
 [ 'their', 0 ],
 [ 'them', 0 ],
 [ 'then', 0 ],
 [ 'there', 0 ],
 [ 'therefore', 0 ],
 [ 'these', 0 ],
 [ 'they', 0 ],
 [ 'things', 0 ],
 [ 'think', 0 ],
 [ 'this', 0 ],
 [ 'those', 0 ],
 [ 'thread', 0 ],
 [ 'three', 0 ],
 [ 'through', 0 ],
 [ 'tickets', 0 ],
 [ 'time', 0 ],
 [ 'times', 0 ],
 [ 'title', 0 ],
 [ 'to', 0 ],
 [ 'today', 0 ],
 [ 'together', 0 ],
 [ 'too', 0 ],
 [ 'tools', 0 ],
 [ 'top', 0 ],
 [ 'topic', 0 ],
 [ 'total', 0 ],
 [ 'training', 0 ],
 [ 'transport', 0 ],
 [ 'travel', 0 ],
 [ 'treatment', 0 ],
 [ 'try', 0 ],
 [ 'TV', 0 ],
 [ 'two', 0 ],
 [ 'type', 0 ],
 [ 'under', 0 ],
 [ 'united', 0 ],
 [ 'up', 0 ],
 [ 'updated', 0 ],
 [ 'us', 0 ],
 [ 'USA', 0 ],
 [ 'use', 0 ],
 [ 'used', 0 ],
 [ 'user', 0 ],
 [ 'users', 0 ],
 [ 'using', 0 ],
 [ 'value', 0 ],
 [ 'version', 0 ],
 [ 'very', 0 ],
 [ 'via', 0 ],
 [ 'video', 0 ],
 [ 'view', 0 ],
 [ 'visit', 0 ],
 [ 'vs', 0 ],
 [ 'want', 0 ],
 [ 'war', 0 ],
 [ 'was', 0 ],
 [ 'way', 0 ],
 [ 'were', 0 ],
 [ 'what', 0 ],
 [ 'when', 0 ],
 [ 'where', 0 ],
 [ 'whether', 0 ],
 [ 'which', 0 ],
 [ 'while', 0 ],
 [ 'white', 0 ],
 [ 'who', 0 ],
 [ 'why', 0 ],
 [ 'will', 0 ],
 [ 'window', 0 ],
 [ 'windows', 0 ],
 [ 'wireless', 0 ],
 [ 'with', 0 ],
 [ 'within', 0 ],
 [ 'without', 0 ],
 [ 'women', 0 ],
 [ 'work', 0 ],
 [ 'working', 0 ],
 [ 'world', 0 ],
 [ 'worldwide', 0 ],
 [ 'would', 0 ],
 [ 'written', 0 ],
 [ 'yahoo', 0 ],
 [ 'year', 0 ],
 [ 'years', 0 ],
 [ 'yes', 0 ],
 [ 'yet', 0 ],
 [ 'you', 0 ],
 [ 'your', 0 ],
];

var WordCount = Words.length;

var Abbreviations = [
 [ 'AA', 'After all' ],
 [ 'AB', 'All before' ],
 [ 'ABT', 'About' ],
 [ 'ADEE', 'Addressee' ],
 [ 'ADR', 'Address' ],
 [ 'ADS', 'Address' ],
 [ 'AGN', 'Again' ],
 [ 'AM', 'Amplitude Modulation' ],
 [ 'ANT', 'Antenna' ],
 [ 'B4', 'Before' ],
 [ 'BCI', 'Broadcast Interference' ],
 [ 'BCL', 'Broadcast Listener' ],
 [ 'BCNU', 'Be seeing you' ],
 [ 'BK', 'Break or Break-in' ],
 [ 'BN', 'All between or Been' ],
 [ 'BT', 'Separation or add a space' ],
 [ 'BTR', 'Better' ],
 [ 'BUG', 'Semi-Automatic key' ],
 [ 'C', 'Yes or Correct' ],
 [ 'CFM', 'Confirm or  I confirm' ],
 [ 'CK', 'Check' ],
 [ 'CKT', 'Circuit' ],
 [ 'CL', 'I am closing my station or Call' ],
 [ 'CLD', 'Called' ],
 [ 'CLG', 'Calling' ],
 [ 'CNT', 'Cant' ],
 [ 'CONDX', 'Conditions' ],
 [ 'CQ', 'Calling any station' ],
 [ 'CU', 'See you' ],
 [ 'CUL', 'See you later' ],
 [ 'CUM', 'Come' ],
 [ 'CW', 'Continuous-wave' ],
 [ 'DA  Day', 'Day' ],
 [ 'DE', 'From or This is' ],
 [ 'DIFF', 'Difference' ],
 [ 'DLD', 'Delivered' ],
 [ 'DLVD', 'Delivered' ],
 [ 'DN', 'Down' ],
 [ 'DR', 'Dear' ],
 [ 'DX', 'Distance' ],
 [ 'EL', 'Element' ],
 [ 'ES', 'Fine business or Excellent' ],
 [ 'FER', 'For' ],
 [ 'FM', 'From' ],
 [ 'GA', 'Go ahead or Good afternoon' ],
 [ 'GB', 'Goodbye or God bless' ],
 [ 'GD', 'Good' ],
 [ 'GE', 'Good Evening' ],
 [ 'GESS', 'Guess' ],
 [ 'GG', 'Going' ],
 [ 'GM', 'Good morning' ],
 [ 'GN', 'Good night' ],
 [ 'GND', 'Ground' ],
 [ 'GUD', 'Good' ],
 [ 'GV', 'Give' ],
 [ 'GVG', 'Giving' ],
 [ 'HH', 'Error in sending' ],
 [ 'HI', 'The telegraph laugh' ],
 [ 'HPE', 'Hope' ],
 [ 'HQ', 'Headquarters' ],
 [ 'HR', 'Here or Hear' ],
 [ 'HV', 'Have' ],
 [ 'HW', 'How or How copy?' ],
 [ 'IMI', 'Repeat or Say again' ],
 [ 'INFO', 'Info' ],
 [ 'LID', 'A poor operator' ],
 [ 'LNG', 'Long' ],
 [ 'LTR', 'Later or letter' ],
 [ 'LV', 'Leave' ],
 [ 'LVG', 'Leaving' ],
 [ 'MA', 'Milliamperes' ],
 [ 'MILL', 'Typewriter' ],
 [ 'MILS', 'Milliamperes' ],
 [ 'MSG', 'Prefix to message' ],
 [ 'N', 'No, Negative, Incorrect or No More' ],
 [ 'NCS', 'Net Control Station' ],
 [ 'NIL', 'Nothing or I have nothing for you' ],
 [ 'NM', 'No more' ],
 [ 'NR', 'Number' ],
 [ 'NW', 'Now or I resume transmission' ],
 [ 'OB', 'Old boy' ],
 [ 'OC', 'Old chap' ],
 [ 'OM', 'Old man' ],
 [ 'OP', 'Operator' ],
 [ 'OPR', 'Operator' ],
 [ 'OT', 'Oldtimer or Old top' ],
 [ 'PBL', 'Preamble' ],
 [ 'PKG', 'Package' ],
 [ 'PSE', 'Please' ],
 [ 'PT', 'Point' ],
 [ 'PWR', 'Power' ],
 [ 'PX', 'Press' ],
 [ 'R', 'Received as transmitted, Are or Decimal Point' ],
 [ 'RC', 'Ragchew or informal conversation' ],
 [ 'RCD', 'Received' ],
 [ 'RCVR', 'Receiver' ],
 [ 'RE', 'Concerning; Regarding' ],
 [ 'REF', 'Refer to, Referring to or Reference' ],
 [ 'RFI', 'Radiofrequency interference' ],
 [ 'RIG', 'Station equipment' ],
 [ 'RPT', 'Repeat or Report' ],
 [ 'RST', 'Readability, strength or tone' ],
 [ 'RTTY', 'Radio teletype' ],
 [ 'RX', 'Receive or Receiver' ],
 [ 'SASE', 'Self-addressed or stamped envelope' ],
 [ 'SED', 'Said' ],
 [ 'SEZ', 'Says' ],
 [ 'SGD', 'Signed' ],
 [ 'SIG', 'Signature or Signal' ],
 [ 'SINE', 'Operators personal initials or nickname' ],
 [ 'SKED', 'Schedule' ],
 [ 'SRI', 'Sorry' ],
 [ 'SS', 'Sweepstakes' ],
 [ 'SSB', 'Single side band' ],
 [ 'STN', 'Station' ],
 [ 'SUM', 'Some' ],
 [ 'SVC', 'Prefix to service message' ],
 [ 'T', 'Zero' ],
 [ 'T/R', 'Transmit/Receive' ],
 [ 'TFC', 'Traffic' ],
 [ 'TKS', 'Thanks' ],
 [ 'TMW', 'Tomorrow' ],
 [ 'TNX', 'Thanks' ],
 [ 'TR', 'Transmit' ],
 [ 'TRIX', 'Tricks' ],
 [ 'TT', 'That' ],
 [ 'TTS', 'That is' ],
 [ 'TU', 'Thank you' ],
 [ 'TVI', 'Television interference' ],
 [ 'TX', 'Transmitter or Transmit' ],
 [ 'TXT', 'Text' ],
 [ 'U', 'You' ],
 [ 'UR', 'Your or Youre' ],
 [ 'URS', 'Yours' ],
 [ 'VFB', 'Very fine business' ],
 [ 'VFO', 'Variable Frequency Oscillator' ],
 [ 'VY', 'Very' ],
 [ 'W', 'Watts' ],
 [ 'WA', 'Word after' ],
 [ 'WB', 'Word before' ],
 [ 'WD', 'Word' ],
 [ 'WDS', 'Words' ],
 [ 'WID', 'With' ],
 [ 'WKD', 'Worked' ],
 [ 'WKG', 'Working' ],
 [ 'WL', 'Well or Will' ],
 [ 'WPM', 'Words Per Minute' ],
 [ 'WRD', 'Word' ],
 [ 'WUD', 'Would' ],
 [ 'WX', 'Weather' ],
 [ 'XCVR', 'Transceiver' ],
 [ 'XMTR', 'Transmitter' ],
 [ 'XTAL', 'Crystal' ],
 [ 'XYL', 'Wife' ],
 [ 'YL', 'Young lady' ],
 [ 'YR', 'Year' ],
];

var AbbreviationCount = Abbreviations.length;


